// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHEXcILy6T1jcB3E9LtgvZWdV0nRr7LLc',
    appId: '1:44130572852:web:8163c662f1e0d6bedf0861',
    messagingSenderId: '44130572852',
    projectId: 'program-1-cd291',
    authDomain: 'program-1-cd291.firebaseapp.com',
    storageBucket: 'program-1-cd291.firebasestorage.app',
    measurementId: 'G-TG28C7XCV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUHhkX6gk76rMiKpxpIrC6YS4GZWDv1Gk',
    appId: '1:44130572852:android:7cc533108e07eaeedf0861',
    messagingSenderId: '44130572852',
    projectId: 'program-1-cd291',
    storageBucket: 'program-1-cd291.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPMyLLJHS3WE1Ptlm29FpgI3dzPGPbOhY',
    appId: '1:44130572852:ios:a59eac93131a77e5df0861',
    messagingSenderId: '44130572852',
    projectId: 'program-1-cd291',
    storageBucket: 'program-1-cd291.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPMyLLJHS3WE1Ptlm29FpgI3dzPGPbOhY',
    appId: '1:44130572852:ios:a59eac93131a77e5df0861',
    messagingSenderId: '44130572852',
    projectId: 'program-1-cd291',
    storageBucket: 'program-1-cd291.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHEXcILy6T1jcB3E9LtgvZWdV0nRr7LLc',
    appId: '1:44130572852:web:8b47d752100c7429df0861',
    messagingSenderId: '44130572852',
    projectId: 'program-1-cd291',
    authDomain: 'program-1-cd291.firebaseapp.com',
    storageBucket: 'program-1-cd291.firebasestorage.app',
    measurementId: 'G-7JHN92P8Z0',
  );
}
